---
title: "Clase 8"
author: "Alvaro Chirino Gutierrez"
date: "6/8/2020"
output: 
  html_document:
    toc: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Librería ggplot

  * Data
  * Estética
  * Geometría
  
```{r}
rm(list=ls())
load(url("https://github.com/AlvaroLimber/R_aru/raw/master/data/eh19.RData"))
z<-mean(1:10)
```

La media de los datos es: `r z`. Es el promedio del vector `r 1:10`.

Sea la matriz A: `r matrix(1:10,2,5)`

```{r}
knitr::kable(as.table(matrix(1:10,2,5)))
as.numeric(c("sbchds","23","0.2424"))
```

```{r}
library(ggplot2)
library(dplyr)
ggplot(eh19p,aes(x=ylab,weights=factor))+geom_histogram()
g1<-ggplot(eh19p %>% filter(s02a_03>=15)  ,aes(x=log(ylab),weights=factor))+geom_histogram(colour="blue")
g1+xlab("Log del ingreso laboral")+ylab("Frecuencia")

ggplot(eh19p %>% filter(s02a_03>=15),aes(x=depto,y=log(ylab)),weights=factor)+geom_boxplot()
ggplot(eh19p %>% filter(s02a_03>=15),aes(x=depto,y=log(ylab)),weights=factor)+geom_violin()
ggplot(eh19p %>% filter(s02a_03>=15),aes(x=depto,y=log(ylab)),weights=factor)+geom_jitter()

ggplot(eh19p %>% filter(s02a_03>=15),aes(x=depto,y=log(ylab)),weights=factor)+geom_boxplot()+facet_wrap(~area+s02a_02)

ggplot(eh19p %>% filter(s02a_03>=15),aes(log(ylab)),weights=factor)+geom_density()+facet_wrap(~area+s02a_02,nrow = 1,ncol = 4)
ggplot(eh19p %>% filter(s02a_03>=15),aes(log(ylab)),weights=factor)+geom_density()+facet_grid(~area+s02a_02)

g2<-ggplot(eh19p %>% filter(s02a_03>=15),aes(log(ylab),log(yhogpc)          ,colour=area),weights=factor)+geom_point(alpha=1/3)+geom_smooth(method="lm")
g2+theme_minimal()
g2+theme_bw()
g2+theme_classic()

g3<-ggplot(eh19p %>% filter(s02a_03>=15),aes(log(ylab),log(yhogpc)          ,colour=depto,size=s02a_03,shape=area),weights=factor)+geom_point(alpha=1/3)

plotly::ggplotly(g3)
```

# Shiny




